version: '3.8'
services:
  backend:
    build: ./wastrika_backend
    ports: ["8000:8000"]
    volumes: ["./wastrika_backend:/app"]
    env_file: .env
    depends_on: [redis]
  frontend:
    build: ./wastrika_frontend
    ports: ["5173:5173"]
    volumes: ["./wastrika_frontend:/app"]
  redis:
    image: "redis:alpine"
    ports: ["6379:6379"]
  worker:
    build: ./wastrika_backend
    command: celery -A app.worker.celery_worker worker --loglevel=info
    depends_on: [redis, backend]